In [1]:
print('hello')

hello


In [ ]:
while True:
    a=input('Enter:')
    if(a=='summer'):
        print('It is summer')
    elif(a=='winter'):
        print('It is winter')
    elif(a=='monsoon'):
        print('It is monsoon')
    else:
        print('Invalid')

In [22]:
#list are MUTABLE - can be changed
fruits=['apple','orange']
fruits

['apple', 'orange']

In [5]:
fruits.append('mango')
fruits

['apple', 'orange', 'mango', 'mango']

In [6]:
fruits.insert(2,'banana')

In [7]:
fruits

['apple', 'orange', 'banana', 'mango', 'mango']

In [8]:
fruits.remove('mango')

In [9]:
fruits

['apple', 'orange', 'banana', 'mango']

In [10]:
fruits.remove('mango')
fruits

['apple', 'orange', 'banana']

In [11]:
fruits.append('mango')
fruits

['apple', 'orange', 'banana', 'mango']

In [12]:
fruits.pop(2)

'banana'

In [14]:
fruits.reverse()
fruits

['apple', 'orange', 'mango']

In [16]:
fruits.reverse()

In [17]:
fruits

['mango', 'orange', 'apple']

In [18]:
t=(1,2,3,False,'Hi')
print(t)

(1, 2, 3, False, 'Hi')


In [19]:
type(t)

tuple

In [20]:
#tuple is IMMUTABLE- cannot be changed
t.append('hello')

AttributeError: 'tuple' object has no attribute 'append'

In [24]:
#set is UNORDERED
s={1,2,3,4,5}
s

{1, 2, 3, 4, 5}

In [29]:
q={6,7,8,1,9,0}
q

{0, 1, 6, 7, 8, 9}

In [30]:
#Union of sets
s | q

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

In [36]:
#Intersection of sets
s & q

{1}

In [4]:
#Dictionary 
di={1:'hi',2:'hello'}
di

{1: 'hi', 2: 'hello'}

In [4]:
import numpy as np
a=np.array(1)
type(a)

1


numpy.ndarray

In [6]:
#size of the array
a.size

1

In [13]:
#Dimension of the array
a.ndim
# 0 dimension is known as scaler

0

In [12]:
#No of rows and columns
a.shape

()

In [21]:
b=np.array([1,2,3])
b

array([1, 2, 3])

In [33]:
b.shape
#3 columns and 1 row 
#In 1d it is (col,rows)

(3,)

In [24]:
b.size # No of elements

3

In [27]:
b.ndim #Dimension - Vector (1 dimension)

1

In [29]:
c=np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
c.ndim # Matrix (2 dimensional)

2

In [31]:
c.size

6

In [34]:
c.shape 
#In 2d it's (rows,cols)

(2, 3)

In [42]:
#np numpy, random package (collection of Libraries), randint -Library
np.random.seed(0) #inorder to make the randint fixed
d = np.random.randint(0, 10, 10) # I want 10 random Integers into the range of 1 to 10
print(d)

[5 0 3 3 7 9 3 5 2 4]


In [49]:
d.reshape(1,10) #1d (cols,rows)

array([[5, 0, 3, 3, 7, 9, 3, 5, 2, 4]])

In [50]:
d.reshape(2,5) #2d (rows,cols)

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4]])

In [54]:
x=np.ones(5) #For white color - (255)
x

array([1., 1., 1., 1., 1.])

In [56]:
y = np.zeros(88) #For black color - (0)
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])